# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/zhang/ordonnancement

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/zhang/ordonnancement

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/zhang/ordonnancement/CMakeFiles /home/zhang/ordonnancement/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/zhang/ordonnancement/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named heuristique

# Build rule for target.
heuristique: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 heuristique
.PHONY : heuristique

# fast build rule for target.
heuristique/fast:
	$(MAKE) -f CMakeFiles/heuristique.dir/build.make CMakeFiles/heuristique.dir/build
.PHONY : heuristique/fast

src/exactSolution.o: src/exactSolution.c.o

.PHONY : src/exactSolution.o

# target to build an object file
src/exactSolution.c.o:
	$(MAKE) -f CMakeFiles/heuristique.dir/build.make CMakeFiles/heuristique.dir/src/exactSolution.c.o
.PHONY : src/exactSolution.c.o

src/exactSolution.i: src/exactSolution.c.i

.PHONY : src/exactSolution.i

# target to preprocess a source file
src/exactSolution.c.i:
	$(MAKE) -f CMakeFiles/heuristique.dir/build.make CMakeFiles/heuristique.dir/src/exactSolution.c.i
.PHONY : src/exactSolution.c.i

src/exactSolution.s: src/exactSolution.c.s

.PHONY : src/exactSolution.s

# target to generate assembly for a file
src/exactSolution.c.s:
	$(MAKE) -f CMakeFiles/heuristique.dir/build.make CMakeFiles/heuristique.dir/src/exactSolution.c.s
.PHONY : src/exactSolution.c.s

src/genetic.o: src/genetic.c.o

.PHONY : src/genetic.o

# target to build an object file
src/genetic.c.o:
	$(MAKE) -f CMakeFiles/heuristique.dir/build.make CMakeFiles/heuristique.dir/src/genetic.c.o
.PHONY : src/genetic.c.o

src/genetic.i: src/genetic.c.i

.PHONY : src/genetic.i

# target to preprocess a source file
src/genetic.c.i:
	$(MAKE) -f CMakeFiles/heuristique.dir/build.make CMakeFiles/heuristique.dir/src/genetic.c.i
.PHONY : src/genetic.c.i

src/genetic.s: src/genetic.c.s

.PHONY : src/genetic.s

# target to generate assembly for a file
src/genetic.c.s:
	$(MAKE) -f CMakeFiles/heuristique.dir/build.make CMakeFiles/heuristique.dir/src/genetic.c.s
.PHONY : src/genetic.c.s

src/heuristiqueA.o: src/heuristiqueA.c.o

.PHONY : src/heuristiqueA.o

# target to build an object file
src/heuristiqueA.c.o:
	$(MAKE) -f CMakeFiles/heuristique.dir/build.make CMakeFiles/heuristique.dir/src/heuristiqueA.c.o
.PHONY : src/heuristiqueA.c.o

src/heuristiqueA.i: src/heuristiqueA.c.i

.PHONY : src/heuristiqueA.i

# target to preprocess a source file
src/heuristiqueA.c.i:
	$(MAKE) -f CMakeFiles/heuristique.dir/build.make CMakeFiles/heuristique.dir/src/heuristiqueA.c.i
.PHONY : src/heuristiqueA.c.i

src/heuristiqueA.s: src/heuristiqueA.c.s

.PHONY : src/heuristiqueA.s

# target to generate assembly for a file
src/heuristiqueA.c.s:
	$(MAKE) -f CMakeFiles/heuristique.dir/build.make CMakeFiles/heuristique.dir/src/heuristiqueA.c.s
.PHONY : src/heuristiqueA.c.s

src/heuristiqueErkang.o: src/heuristiqueErkang.c.o

.PHONY : src/heuristiqueErkang.o

# target to build an object file
src/heuristiqueErkang.c.o:
	$(MAKE) -f CMakeFiles/heuristique.dir/build.make CMakeFiles/heuristique.dir/src/heuristiqueErkang.c.o
.PHONY : src/heuristiqueErkang.c.o

src/heuristiqueErkang.i: src/heuristiqueErkang.c.i

.PHONY : src/heuristiqueErkang.i

# target to preprocess a source file
src/heuristiqueErkang.c.i:
	$(MAKE) -f CMakeFiles/heuristique.dir/build.make CMakeFiles/heuristique.dir/src/heuristiqueErkang.c.i
.PHONY : src/heuristiqueErkang.c.i

src/heuristiqueErkang.s: src/heuristiqueErkang.c.s

.PHONY : src/heuristiqueErkang.s

# target to generate assembly for a file
src/heuristiqueErkang.c.s:
	$(MAKE) -f CMakeFiles/heuristique.dir/build.make CMakeFiles/heuristique.dir/src/heuristiqueErkang.c.s
.PHONY : src/heuristiqueErkang.c.s

src/init.o: src/init.c.o

.PHONY : src/init.o

# target to build an object file
src/init.c.o:
	$(MAKE) -f CMakeFiles/heuristique.dir/build.make CMakeFiles/heuristique.dir/src/init.c.o
.PHONY : src/init.c.o

src/init.i: src/init.c.i

.PHONY : src/init.i

# target to preprocess a source file
src/init.c.i:
	$(MAKE) -f CMakeFiles/heuristique.dir/build.make CMakeFiles/heuristique.dir/src/init.c.i
.PHONY : src/init.c.i

src/init.s: src/init.c.s

.PHONY : src/init.s

# target to generate assembly for a file
src/init.c.s:
	$(MAKE) -f CMakeFiles/heuristique.dir/build.make CMakeFiles/heuristique.dir/src/init.c.s
.PHONY : src/init.c.s

src/intervalTree.o: src/intervalTree.c.o

.PHONY : src/intervalTree.o

# target to build an object file
src/intervalTree.c.o:
	$(MAKE) -f CMakeFiles/heuristique.dir/build.make CMakeFiles/heuristique.dir/src/intervalTree.c.o
.PHONY : src/intervalTree.c.o

src/intervalTree.i: src/intervalTree.c.i

.PHONY : src/intervalTree.i

# target to preprocess a source file
src/intervalTree.c.i:
	$(MAKE) -f CMakeFiles/heuristique.dir/build.make CMakeFiles/heuristique.dir/src/intervalTree.c.i
.PHONY : src/intervalTree.c.i

src/intervalTree.s: src/intervalTree.c.s

.PHONY : src/intervalTree.s

# target to generate assembly for a file
src/intervalTree.c.s:
	$(MAKE) -f CMakeFiles/heuristique.dir/build.make CMakeFiles/heuristique.dir/src/intervalTree.c.s
.PHONY : src/intervalTree.c.s

src/job.o: src/job.c.o

.PHONY : src/job.o

# target to build an object file
src/job.c.o:
	$(MAKE) -f CMakeFiles/heuristique.dir/build.make CMakeFiles/heuristique.dir/src/job.c.o
.PHONY : src/job.c.o

src/job.i: src/job.c.i

.PHONY : src/job.i

# target to preprocess a source file
src/job.c.i:
	$(MAKE) -f CMakeFiles/heuristique.dir/build.make CMakeFiles/heuristique.dir/src/job.c.i
.PHONY : src/job.c.i

src/job.s: src/job.c.s

.PHONY : src/job.s

# target to generate assembly for a file
src/job.c.s:
	$(MAKE) -f CMakeFiles/heuristique.dir/build.make CMakeFiles/heuristique.dir/src/job.c.s
.PHONY : src/job.c.s

src/tool.o: src/tool.c.o

.PHONY : src/tool.o

# target to build an object file
src/tool.c.o:
	$(MAKE) -f CMakeFiles/heuristique.dir/build.make CMakeFiles/heuristique.dir/src/tool.c.o
.PHONY : src/tool.c.o

src/tool.i: src/tool.c.i

.PHONY : src/tool.i

# target to preprocess a source file
src/tool.c.i:
	$(MAKE) -f CMakeFiles/heuristique.dir/build.make CMakeFiles/heuristique.dir/src/tool.c.i
.PHONY : src/tool.c.i

src/tool.s: src/tool.c.s

.PHONY : src/tool.s

# target to generate assembly for a file
src/tool.c.s:
	$(MAKE) -f CMakeFiles/heuristique.dir/build.make CMakeFiles/heuristique.dir/src/tool.c.s
.PHONY : src/tool.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... heuristique"
	@echo "... src/exactSolution.o"
	@echo "... src/exactSolution.i"
	@echo "... src/exactSolution.s"
	@echo "... src/genetic.o"
	@echo "... src/genetic.i"
	@echo "... src/genetic.s"
	@echo "... src/heuristiqueA.o"
	@echo "... src/heuristiqueA.i"
	@echo "... src/heuristiqueA.s"
	@echo "... src/heuristiqueErkang.o"
	@echo "... src/heuristiqueErkang.i"
	@echo "... src/heuristiqueErkang.s"
	@echo "... src/init.o"
	@echo "... src/init.i"
	@echo "... src/init.s"
	@echo "... src/intervalTree.o"
	@echo "... src/intervalTree.i"
	@echo "... src/intervalTree.s"
	@echo "... src/job.o"
	@echo "... src/job.i"
	@echo "... src/job.s"
	@echo "... src/tool.o"
	@echo "... src/tool.i"
	@echo "... src/tool.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

